name: PR test

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: npm install
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
        run: |
          npm i --legacy-peer-deps
      - name: build prismui-formula
        run: |
          npm run build --workspace prismui\-formula
      - name: build prismui-core
        run: |
          npm run build --workspace prismui\-core
      - name: build prismui-ui
        run: |
          npm run build --workspace prismui\-ui
      - name: build prismui-office-viewer
        run: |
          npm run build --workspace prismui\-office\-viewer
      - name: build prismui
        run: |
          npm run build --workspace prismui
      - name: check schema.json
        run: |
          cp ./packages/amis/schema.json .
      - name: build prismui-theme-editor-helper
        run: |
          npm run build --workspace prismui\-theme\-editor\-helper
      - name: build prismui-editor-core
        run: |
          npm run build --workspace prismui\-editor\-core
      - name: build prismui-editor
        run: |
          npm run build --workspace prismui\-editor
      - name: build vite-plugin-prismui
        run: |
          npm run build --workspace vite\-plugin\-prismui
      - name: typescript check
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
        run: |
          npm run typecheck
      - name: test
        run: |
          npm test --workspaces
          sh deploy-gh-pages.sh
